spring:
  profiles:
    active: local

server:
  forward-headers-strategy: framework

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml, application-swagger.yml, application-oauth-local.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml, application-swagger.yml, application-oauth.yml